version: '3'

services:
  
  app:
    image: brennoferreira/node-app:fullcycle
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 40s docker-entrypoint.sh
    tty: true
    command: ["node", "index.js"]
    networks: 
      - node-network
    ports:
      - "3000:3000"
    depends_on: 
      - db

  nginx:
    image: brennoferreira/nginx:fullcycle
    container_name: nginx
    tty: true
    networks: 
      - node-network
    ports:
      - "8080:80"
    depends_on: 
      - app

  db:
    image: brennoferreira/mysql:fullcycle
    container_name: db
    restart: always
    tty: true
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
    networks: 
      - node-network

networks: 
  node-network:
    driver: bridge